# Generated by Django 4.2.3 on 2023-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annonces", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annonce",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
